### PR TITLE
Add subpath for S3 based on current date

### PR DESCRIPTION
**Pull request by skryzhny**

### CODE REVIEW

**Comment by maorfr** [comment]
i suggest that instead of uploading to a single directory, we upload to multiple in cases when "today" is also time for a weekly backup and for a daily back (as an example).

i think it will be rather simple:

1. change --subfolder to accept a list of paths: https://stackoverflow.com/questions/15753701/how-can-i-pass-a-list-as-a-command-line-argument-with-argparse (edited) 

2. do this for each subfolder: https://github.com/app-sre/git-keeper/blob/master/git-keeper.py#L101-L106
3. change SUBPATH to represent a list: https://github.com/app-sre/git-keeper/pull/18/files#diff-1b0c2b516b83393edb7200ad5ff12181R34-R41

@skryzhny and I had this discussion internally, here are some thoughts:
- it will add some complexity to both scripts
- it will increase storage/upload time, although not over time, as we have retention policies
- if we have an incident, a missing backup in the daily directory may be confusing

@jmelis wdyt?

**Comment by jmelis** [comment]
+1 to the idea. Please create a JIRA to do this in the future.

@skryzhny can we merge this PR as it is?

LGTM

**Comment by skryzhny** [comment]
As for me logic of uploading to multiple subfolders is jenkins job part.
And ideally we should handle that with S3 lifecycle policies, in case of Monday instead of deleting old backups they need to go to weekly subfolder etc.

**Comment by jmelis** [comment]
That's not a bad idea  Serhii, let's discuss it in the JIRA

**Comment by maorfr** [comment]
using lifecycle policies to move backups around will couple this tool to AWS s3. i don't think we want that.

**Pull request merged**
